import io
f = 'c:/Users/23747/Documents/OmniCore/frontend/src/components/ChatView.vue'
c = io.open(f, 'r', encoding='utf-8').read()
c = c.replace('<h1>欢迎使用 OmniCore</h1>', '<h1>{{ t(\'welcome_title\') }}</h1>')
c = c.replace('<p>我是您的 AI 智能助手，请在下文输入问题开始对话。</p>', '<p>{{ t(\'welcome_desc\') }}</p>')
c = c.replace('<span class="quick-icon">✏️</span> 写代码', '<span class="quick-icon">✏️</span> {{ t(\'quick_code\') }}')
c = c.replace('<span class="quick-icon">📉</span> 解释概念', '<span class="quick-icon">📉</span> {{ t(\'quick_explain\') }}')
c = c.replace('<span class="quick-icon">📬</span> 搜索新闻', '<span class="quick-icon">📬</span> {{ t(\'quick_news\') }}')
c = c.replace("chatStore.setChatInput('帮我写一个Python冒泡排序')", "chatStore.setChatInput(t('quick_code_prompt'))")
c = c.replace("chatStore.setChatInput('用通俗的语言解释什么是机器学习')", "chatStore.setChatInput(t('quick_explain_prompt'))")
c = c.replace("chatStore.setChatInput('帮我总结一下近期的AI行业新闻')", "chatStore.setChatInput(t('quick_news_prompt'))")
io.open(f, 'w', encoding='utf-8').write(c)
f2 = 'c:/Users/23747/Documents/OmniCore/frontend/src/components/ModelMarket.vue'
c2 = io.open(f2, 'r', encoding='utf-8').read()
c2 = c2.replace('background: #fff8f0;', 'background: var(--warning-light, #fff8f0);')
c2 = c2.replace('border-color: #e67e22;', 'border-color: var(--warning, #e67e22);')
c2 = c2.replace('background: #d5f5e3;', 'background: var(--success-light, #d5f5e3);')
c2 = c2.replace('color: #27ae60;', 'color: var(--success, #27ae60);')
c2 = c2.replace('background: #fdebd0;', 'background: var(--warning-light, #fdebd0);')
c2 = c2.replace('color: #e67e22;', 'color: var(--warning, #e67e22);')
c2 = c2.replace('background: #4a90d9;', 'background: var(--primary, #4a90d9);')
c2 = c2.replace('border-color: #4a90d9;', 'border-color: var(--primary, #4a90d9);')
c2 = c2.replace('background: #357abd;', 'background: var(--primary-hover, #357abd);')
c2 = c2.replace('color: #e74c3c;', 'color: var(--danger, #e74c3c);')
c2 = c2.replace('border-color: #e74c3c;', 'border-color: var(--danger, #e74c3c);')
c2 = c2.replace('background: #e74c3c;', 'background: var(--danger, #e74c3c);')
c2 = c2.replace('background: #c0392b;', 'background: var(--danger-light, #c0392b);')
c2 = c2.replace('background: #f39c12;', 'background: var(--warning, #f39c12);')
c2 = c2.replace('border-color: #f39c12;', 'border-color: var(--warning, #f39c12);')
c2 = c2.replace('background: #d68910;', 'background: var(--warning-light, #d68910);')
c2 = c2.replace('background: #8e44ad;', 'background: var(--purple, #8e44ad);')
c2 = c2.replace('border-color: #8e44ad;', 'border-color: var(--purple, #8e44ad);')
c2 = c2.replace('background: #7d3c98;', 'background: var(--purple, #7d3c98);')
c2 = c2.replace('color: #8e44ad;', 'color: var(--purple, #8e44ad);')
c2 = c2.replace('border-color: #27ae60;', 'border-color: var(--success, #27ae60);')
c2 = c2.replace('background: #27ae60;', 'background: var(--success, #27ae60);')
c2 = c2.replace('background: #219a52;', 'background: var(--success-light, #219a52);')
c2 = c2.replace('background: #fdecea;', 'background: var(--danger-light, #fdecea);')
c2 = c2.replace('border: 1px solid #f5c6cb;', 'border: 1px solid var(--danger, #f5c6cb);')
c2 = c2.replace('color: #c0392b;', 'color: var(--danger, #c0392b);')
c2 = c2.replace('color: #721c24;', 'color: var(--danger, #721c24);')
c2 = c2.replace('background: linear-gradient(90deg, #4a90d9, #357abd);', 'background: var(--primary-gradient, linear-gradient(90deg, #4a90d9, #357abd));')
c2 = c2.replace('background: #e9ecef;', 'background: var(--bg-muted, #e9ecef);')
c2 = c2.replace('background: var(--bg-secondary, #fafafa);', 'background: var(--bg-card, #fafafa);')
c2 = c2.replace('background: var(--bg-secondary, #f5f5f5);', 'background: var(--bg-muted, #f5f5f5);')
c2 = c2.replace('color: var(--text-primary, #333);', 'color: var(--text, #333);')
io.open(f2, 'w', encoding='utf-8').write(c2)
